export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_ERROR = "SET_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const LOADING = "LOADING";

export const SET_RESTAURANT_PHOTO = "SET_RESTAURANT_PHOTO";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const SET_START_RESTAURANTS = "SET_START_RESTAURANTS";
export const LOADING_RESTAURANTS = "LOADING_RESTAURANTS";

export const CHECK_ADD_REVIEW_USER = "CHECK_ADD_REVIEW_USER";
export const GET_REVIEWS = "GET_REVIEWS";
export const SET_START_REVIEWS = "SET_START_REVIEWS";
